apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    stage: dev
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
    - port: 80
      targetPort: 81


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-public
spec:
  selector:
    app: nginx
    stage: dev
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80

