apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    stage: dev
    my_label: my_label
spec:
  containers: 
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
      - containerPort: 81
    resources:
        limits:
          memory: "256Mi"
          cpu: "1000m"
        requests:
          memory: "128Mi"
          cpu: "250m"

